language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-pdemail' ]; then cd .. && eval "mv $currentfolder generator-pdemail" && cd generator-pdemail; fi

